"""Shader source composition.

Each pass is assembled into one GLSL translation unit:

===========================  ==================================================
``#version`` + uniform block  generated prelude (Shadertoy's uniform set)
``common.glsl``               optional, shared by every pass
the pass source              e.g. ``image.glsl``
``main()`` wrapper           calls ``mainImage(fragColor, fragCoord)``
===========================  ==================================================

Because generated code is prepended, a driver error on "line 61" is nowhere
near line 61 of the file the user wrote. Rather than emit ``#line`` directives
(whose second argument is a *source-string number* in core GLSL, not a
filename, and whose handling varies between drivers), we keep an explicit
per-line origin table and translate diagnostics ourselves. That is fully
deterministic and driver-independent.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from shadertoy_local.project import PassSpec, Project, ProjectError

#: GLSL 330 core is the desktop equivalent of Shadertoy's GLSL ES 3.0.
DEFAULT_GLSL_VERSION = 330

_MAIN_IMAGE_RE = re.compile(r"\bvoid\s+mainImage\s*\(", re.MULTILINE)
_INCLUDE_RE = re.compile(r'^\s*#\s*include\s+[<"]([^>"]+)[>"]\s*$')
_MAX_INCLUDE_DEPTH = 16

VERTEX_SHADER = """#version {version} core
in vec2 _st_position;
void main() {{
    gl_Position = vec4(_st_position, 0.0, 1.0);
}}
"""


@dataclass(frozen=True)
class Origin:
    """Where a composed line came from."""

    file: str
    line: int


@dataclass
class ComposedShader:
    """A composed fragment shader plus its line provenance."""

    pass_name: str
    source: str
    #: ``origins[i]`` describes composed line ``i + 1``; ``None`` = generated.
    origins: list[Origin | None] = field(default_factory=list)

    def origin_of(self, composed_line: int) -> Origin | None:
        """Map a 1-based composed line number back to user source."""
        index = composed_line - 1
        if 0 <= index < len(self.origins):
            return self.origins[index]
        return None

    def nearest_origin(self, composed_line: int) -> Origin | None:
        """Best-effort origin, searching upward for generated/out-of-range lines.

        Drivers sometimes report the line *after* a construct, or a line inside
        our generated wrapper; attributing that to the last real user line is
        far more useful than reporting nothing.
        """
        direct = self.origin_of(composed_line)
        if direct is not None:
            return direct
        for index in range(min(composed_line, len(self.origins)) - 1, -1, -1):
            if self.origins[index] is not None:
                return self.origins[index]
        return None

    def numbered_source(self) -> str:
        """The composed source with line numbers, for debugging."""
        width = len(str(len(self.origins)))
        out = []
        for i, text in enumerate(self.source.splitlines(), start=1):
            origin = self.origin_of(i)
            tag = f"  // {origin.file}:{origin.line}" if origin else ""
            out.append(f"{i:>{width}} | {text}{tag}")
        return "\n".join(out)


class _Builder:
    """Accumulates lines while tracking each line's origin."""

    def __init__(self) -> None:
        self.texts: list[str] = []
        self.origins: list[Origin | None] = []

    def emit(self, text: str = "") -> None:
        for line in text.split("\n"):
            self.texts.append(line)
            self.origins.append(None)

    def emit_user(self, text: str, file: str, first_line: int = 1) -> None:
        for offset, line in enumerate(text.split("\n")):
            self.texts.append(line)
            self.origins.append(Origin(file=file, line=first_line + offset))

    def emit_origin(self, text: str, origin: Origin) -> None:
        self.texts.append(text)
        self.origins.append(origin)


def _prelude(version: int, channel_count: int = 4) -> str:
    """Shadertoy's uniform set, plus small compatibility shims."""
    samplers = "\n".join(
        f"uniform sampler2D iChannel{i};" for i in range(channel_count)
    )
    return f"""#version {version} core

// ---- generated by shadertoy-local: Shadertoy uniform interface ----
uniform vec3  iResolution;           // viewport resolution (pixels)
uniform float iTime;                 // shader playback time (seconds)
uniform float iTimeDelta;            // time since previous frame (seconds)
uniform float iFrameRate;            // frames per second
uniform int   iFrame;                // frame index
uniform float iChannelTime[4];       // per-channel playback time
uniform vec3  iChannelResolution[4]; // per-channel resolution
uniform vec4  iMouse;                // xy = current, zw = click (see docs)
uniform vec4  iDate;                 // (year, month, day, seconds)
uniform float iSampleRate;           // audio sample rate
{samplers}

#define HW_PERFORMANCE 1
// Legacy spellings still common in shaders copied from Shadertoy/GLSL ES 1.0.
#define texture2D texture
#define textureCube texture
#define iGlobalTime iTime
// ---- end generated prelude ----
"""


_WRAPPER = """
// ---- generated by shadertoy-local: entry point ----
out vec4 _st_fragColor;
void main() {
    // Shadertoy leaves fragColor undefined; opaque black matches how the site
    // displays shaders that never write alpha.
    vec4 _st_color = vec4(0.0, 0.0, 0.0, 1.0);
    mainImage(_st_color, gl_FragCoord.xy);
    _st_fragColor = _st_color;
}
"""


def _expand_includes(
    source: str,
    display: str,
    root: Path,
    *,
    stack: tuple[Path, ...] = (),
    depth: int = 0,
) -> list[tuple[str, Origin]]:
    """Resolve ``#include "file"`` recursively, returning (text, origin) pairs.

    Shadertoy has no ``#include``; it is supported here because local projects
    benefit from splitting code across files, and the origin table makes the
    line bookkeeping free.
    """
    if depth > _MAX_INCLUDE_DEPTH:
        raise ProjectError(
            f"{display}: #include nested deeper than {_MAX_INCLUDE_DEPTH} levels"
        )

    out: list[tuple[str, Origin]] = []
    for lineno, text in enumerate(source.split("\n"), start=1):
        match = _INCLUDE_RE.match(text)
        if match is None:
            out.append((text, Origin(file=display, line=lineno)))
            continue
        target = (root / match.group(1)).resolve()
        if not target.is_file():
            raise ProjectError(
                f"{display}:{lineno}: #include target not found: {match.group(1)}"
            )
        if target in stack:
            chain = " -> ".join(p.name for p in (*stack, target))
            raise ProjectError(f"{display}:{lineno}: circular #include ({chain})")
        try:
            included = target.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            raise ProjectError(f"{target}: not valid UTF-8: {exc}") from exc
        try:
            rel = target.relative_to(root)
        except ValueError:
            rel = target
        out.extend(
            _expand_includes(
                included,
                str(rel),
                root,
                stack=(*stack, target),
                depth=depth + 1,
            )
        )
    return out


def compose_pass(
    project: Project,
    spec: PassSpec,
    *,
    version: int | None = None,
) -> ComposedShader:
    """Build the full fragment shader for one pass."""
    version = version or int(project.default("glsl_version", DEFAULT_GLSL_VERSION))
    root = project.root

    builder = _Builder()
    builder.emit(_prelude(version))

    if project.common is not None and project.common_path is not None:
        rel_common = _display(project.common_path, root)
        builder.emit(f"\n// ---- {rel_common} ----")
        for text, origin in _expand_includes(
            project.common, rel_common, root, stack=(project.common_path,)
        ):
            builder.emit_origin(text, origin)

    rel_pass = _display(spec.path, root)
    builder.emit(f"\n// ---- {rel_pass} ----")
    for text, origin in _expand_includes(
        spec.source, rel_pass, root, stack=(spec.path,)
    ):
        builder.emit_origin(text, origin)

    builder.emit(_WRAPPER)

    source = "\n".join(builder.texts)
    if not _MAIN_IMAGE_RE.search(source):
        raise ProjectError(
            f"{rel_pass} defines no mainImage function.\n"
            "Every pass needs:\n"
            "    void mainImage(out vec4 fragColor, in vec2 fragCoord) { ... }"
        )

    return ComposedShader(
        pass_name=spec.name, source=source, origins=builder.origins
    )


def vertex_source(version: int | None = None) -> str:
    return VERTEX_SHADER.format(version=version or DEFAULT_GLSL_VERSION)


def _display(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)
